### ISSUE TITLE
Why a separate repo?

### ISSUE THREAD

**Issue by Daniel15** [gaearon/redux-thunk#10]
Just a small question... Why does this small middleware have its own repo? Wouldn't it make more sense for it to live in the `redux` repo too?

**Comment by ro-ka** [comment]
It is an independent middleware, released independently on npm. So it should have it’s own repo, issues and so on.

**Comment by gaearon** [comment]
Yes. We might want to make breaking changes here that aren't related to Redux itself.

**Comment by chuan137** [comment]
I am wondering the same thing. Looks to me, being able to customize the behavior of action is essential to async actions, why not include it in Redux by default.
