### ISSUE TITLE
Typescript definitions are not available with current npm build

### ISSUE THREAD

**Issue by jimsugg** [gaearon/redux-thunk#100]
The recently checked in Typescript definitions are not installed with the current npm build. While there is a version in index.d.ts for redux-thunk in the DefinitelyTyped library, it is different and doesn't work properly. The only way I can really use redux-thunk with Typescript is to manually copy the index.d.ts file from the Github directory after the regular npm install, and then run typings install on the manually copied version. It would be very helpful if you could update the npm build to include the latest Typescript definition files. Thanks!

**Comment by gareth-evans2** [comment]
+1

**Comment by aikoven** [comment]
Released [v2.1.1](https://github.com/gaearon/redux-thunk/releases/tag/v2.1.1) with TypeScript definitions included.
