### ISSUE TITLE
dispatch not returning a promise

### ISSUE THREAD

**Issue by gauravChaturvedi** [gaearon/redux-thunk#102]
My ActionCreator looks like this :

`export function resetRiskProcessCard(cardKey) {
  return (dispatch) => {
    dispatch({
      type: Actions.RESET_RISK_PROCESS_CARD,
      cardKey
    });
  }
}`

And I'm calling it like this 

`this.props.dispatch(ActionCreators.Risk.resetRiskProcessCard(cardKey)).then(() => {
          console.log('then is called !!');
        });`

I get the following error

`Uncaught TypeError: Cannot read property 'then' of undefined`

**Comment by gauravChaturvedi** [comment]
@gaearon Need your help on this please

**Comment by TrySound** [comment]
@gauravChaturvedi You should return the promise in action creator. redux-thunk don't do anything with promise api.

**Comment by alex-wilmer** [comment]
Did you inject the middleware? https://github.com/gaearon/redux-thunk#installation

**Comment by Ronnyrr** [comment]
```javascript
export function getPage(slug) {
  return {
    type: 'GET_PAGE',
    server: true,
    slug
  };
}

export function getPageWithPartners(slug) {
  return function(dispatch, getState) {

    dispatch(getPage(slug))
      .then(page => {
        console.info('promise', page);
      })
  };
}
```

I also need help on this.
Same error `Uncaught TypeError: Cannot read property 'then' of undefined`. But when I make getPage() a Promise() I'll get and `Action should be pure function, use middleware instead`.

So created this:

```javascript
export function getPage(slug) {
  return function(dispatch, getState) {
    return new Promise((resolve, reject) => {
      resolve({
        type: 'GET_PAGE',
        server: true,
        slug
      });
    });
  }
}
``` 

But this only returns the plain object, no results.. 
What am I doing wrong?

**Comment by alex-wilmer** [comment]
@Ronnyrr where are you expecting to get results from? Your example code seems to be missing the actual request for the page (ajax / call to db, etc)

**Comment by Ronnyrr** [comment]
The `getPage()` in the first example fires a socket action which emits the `setPage()`

**Comment by kentoj** [comment]
Is this not closable? The `dispatch()` function is not supposed to return a promise so it doesn't.

**Comment by gauravChaturvedi** [comment]
My bad. Thanks all!

**Comment by aecorredor** [comment]
So if we have an action creator that does not return a promise, we cannot await or chain on it correct? because dispatch alone does not return a promise? even with the use of redux-thunk?

**Comment by ianemv** [comment]
@aecorredor I've been trying also to make an action but it really doesn't return anything. 

Here's a simple test I did,

export function submitLoginThunk(data) {
            return async function (dispatch) {
                try {
                    const response = await postLogin(data);
                    //no error then dispatch 
                } catch (error) {
                    //dispatch error here
                    throw  error;
                }
            }
        }

**Comment by tlareg** [comment]
@ianemv @aecorredor 

We can write it like:

```js
export function submitLoginThunk(data) {
  return function(dispatch) {
    const requestPromise = postLogin(data);
    request.then(function (successResponse) {
      dispatch({
        type: 'SUCCESS_ACTION',
        payload: successResponse
      });
    }, function (error) {
      dispatch({
        type: 'ERROR_ACTION',
        payload: error
      });
    });
    return requestPromise;
  }
}
```

or just

```js
export function submitLoginThunk(data) {
  return function(dispatch) {
    return postLogin(data).then(function (successResponse) {
      dispatch({
        type: 'SUCCESS_ACTION',
        payload: successResponse
      });
    }, function (error) {
      dispatch({
        type: 'ERROR_ACTION',
        payload: error
      });
    });
  }
}
```

or using async/await syntax

```js
export function submitLoginThunk(data) {
  return async function(dispatch) {
    try {
      const successResponse = await postLogin(data);
      dispatch({
        type: 'SUCCESS_ACTION',
        payload: successResponse
      });
    } catch (error) {
      dispatch({
        type: 'ERROR_ACTION',
        payload: error
      });
    }
  }
}
```

if we are using async/await, even if we are not returning anything, function returns Promise
See: [async function on mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)
```
Return value

A Promise which will be resolved with the value returned by the async function, or rejected with an uncaught exception thrown from within the async function.
```

So in this case it is like we would return new Promise(undefined) in non-async function (because function with no explicit return, returns undefined by default).

**Comment by ianemv** [comment]
@tlareg I noticed your sample async/await syntax is the same with mine so component will still don't receive anything. 

my component's function triggered by form submit looks like this

`  async doLogin(){

    try {
               const response = await this.props.submitLoginThunk(values);
               console.log(response);
        
      } catch (error) {
              console.log(error);
    }
  }`

**Comment by tlareg** [comment]
@ianemv ok, then submitLoginThunk should look like:
```js
function submitLoginThunk(data) {
  return async function(dispatch) {
    try {
      const successResponse = await postLogin(data);
      dispatch({
        type: 'SUCCESS_ACTION',
        payload: successResponse
      });
      return successResponse;
    } catch (error) {
      dispatch({
        type: 'ERROR_ACTION',
        payload: error
      });
    }
  }
}
```

**Comment by ianemv** [comment]
@tlareg it's working indeed. now I have to check my setup

**Comment by AlexanderPershin** [comment]
> @gauravChaturvedi You should return the promise in action creator. redux-thunk doesn't do anything with promise api.
Bro, you're epic. Thank you!

**Comment by edward795** [comment]
just temporarily store the response & return it as a promise 
let res,err;

function submitLoginThunk(data) {
  return async function(dispatch) {
    try {
      const successResponse = await postLogin(data);
      res=successResponse;
      dispatch({
        type: 'SUCCESS_ACTION',
        payload: successResponse
      });
    } catch (error) {
      dispatch({
        type: 'ERROR_ACTION',
        payload: error
      });
  err=error;
    }
  if(res){
  return Promise.resolve(res)
    }else{
  return Promise.reject(err)
}


#### Now u can get the response from dispatch call  ### using

submitLoginThunk(data).then((res)=>{
}).catch((err)=>{})
