### ISSUE TITLE
Release typings

### ISSUE THREAD

**Issue by bbenezech** [gaearon/redux-thunk#109]
@aikoven @ulfryk is there something blocking the release of typings (no other changes since 2.1.0)?

**Comment by aikoven** [comment]
I don't think so, but we're only maintaining typings, not doing releases.

cc. @gaearon

**Comment by tdreyno** [comment]
Would love this. It's been almost 6 months since they got added :(

**Comment by prencher** [comment]
This is now causing warnings with TypeScript 2: `npm WARN deprecated @types/redux-thunk@2.1.0: This is a stub types definition for Redux Thunk (https://github.com/gaearon/redux-thunk). Redux Thunk provides its own type definitions, so you don't need @types/redux-thunk installed!`

Which is of course incorrect, since they're not being distributed in the package.

**Comment by brion-fuller** [comment]
I am also seeing this issue with the type definition file not being downloaded on install.

**Comment by aikoven** [comment]
@gaearon Can you please make a release? There are no other changes since last version.

**Comment by davemcgowan** [comment]
there seems to be a new release on npm?   @types/redux-thunk@2.1.32.  that worked for me.

**Comment by gaearon** [comment]
@aikoven 

I'm happy to give the release permissions to you, what's your npm username?

**Comment by gaearon** [comment]
(FWIW this is the first time I see this thread. Please ping me on Twitter next time if I stay silent for months 😄 )

**Comment by aikoven** [comment]
@gaearon It's the same as here. I'm not a `redux-thunk` user, but I am up for making a release if that unburdens you 😉

**Comment by gaearon** [comment]
You got it! Thanks.

**Comment by aikoven** [comment]
Released [v2.1.1](https://github.com/gaearon/redux-thunk/releases/tag/v2.1.1) with TypeScript definitions included.
