### ISSUE TITLE
Uncaught TypeError: (0 , _redux2.default) is not a function(…)

### ISSUE THREAD

**Issue by karlpatrickespiritu** [gaearon/redux-thunk#116]
I don't know if I missed something but I'm getting this error.

````javascript
index.js:17 Uncaught TypeError: (0 , _redux2.default) is not a function(…)
````
Here's my `store.js`
````javascript
import { applyMiddleware, createStore } from 'redux'
import createLogger from 'redux-logger'
import thunk from 'redux-thunk'
import promise from 'redux-promise-middleware'

import reducers from './reducers'

export default createStore(
  reducers,
  applyMiddleware(promise(), thunk, createLogger())
)
````
I'm using:
````cli
"redux-thunk": "^2.1.0",
"redux": "^3.6.0",
````

**Comment by karlpatrickespiritu** [comment]
lol. wrong repo. sorry :zipper_mouth_face:

**Comment by karlpatrickespiritu** [comment]
To anyone might stumble on this kind of error. Here was the issue. 

````javascript
// fails
import combineReducers from "redux"

// correct
import { combineReducers } from "redux"
````

**Comment by techyrajeev** [comment]
@karlpatrickespiritu  thank you very much for the info but can you please explain as well why above works? It will be really helpful. Thanks.

**Comment by WardGubbi** [comment]
@techyrajeev the first one imports the default of redux and names it combineReducers, instead of importing combineReducers itself like the second expression. See [MDN page](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Statements/import)

**Comment by techyrajeev** [comment]
@WardGubbi  Got it! Thank you very much for the link.

**Comment by Gh05d** [comment]
@karlpatrickespiritu thx, you just saved me a lot of time spent guessing :)

**Comment by SorooshPardazCompany** [comment]
use the import like this :
import { componentName } from "redux"

ب[رنامه نویسی اندروید و ios](https://sorooshpardaz.com/mobile-app-android-ios-programming) ,  [آگهی استخدام](https://biikar.com)

**Comment by onmyway133** [comment]
In my case, it is because of 

```js
import connect from 'react-redux'
```

I fixed it by changing to 

```js
import { connect } from 'react-redux'
```

**Comment by ZachW628** [comment]
In my case adding {} to the import from my actions resolved this issue!

**Comment by haron68** [comment]
This was an insane solution but it works, wow!

**Comment by mdehghani65** [comment]
> In my case adding {} to the import from my actions resolved this issue!

thx.saved my night!
