### ISSUE TITLE
Is it a correct use-case for thunk-middleware if the actions payload depends on current store state?

### ISSUE THREAD

**Issue by PSpSynedra** [gaearon/redux-thunk#12]
We stumbled about this, while upgrading to the new react-redux 0.9.0, in which the Connector component was replaced with the connect higher order function.

Given the situation that the result of mapStateToProps is dependent on the actual props like this:
```js
function mapStateToProps( state, ownProps) {
   return {
      field: ownProps.selectors.map( selector => selector(state) )
   };
}
```
you will end up with a new selected state even if the memoized selector functions would return the same objects as the resulting array of the map-function is a new object.

We where thinking about resolving this issue, through the following strategies:

1. Create a compound Selector and pass it as a single property
This selector would only depend on the passed state of the mapStateToProps function and be memoized.
Thus it would return a === equal result for the same state, which would lead to a shallow equally props object but would have to also process the result later like:
```js
function mapStateToProps( state, ownProps) {
   return {
      selectedActionArguments: ownProps.compoundSelector(state)
   };
}
function mapDispatchToProps( dispatch, ownProps ) {
   return bindActionCreators({
      updateAction: ownProps.updateAction
   }, dispatch );
}
function mergeProps( stateProps, dispatchProps, ownProps ) {
   return {
      update: dispatchProps.updateAction.bind( undefined, stateProps.selectedActionArguments )
   }
}
```
Wow it even feels wrong describing it, sorry.

1. Use Thunk-Middleware to select action parameters from the store in the moment of dispatching.
This would reduce the function descriptions to a single mapDispatchToProps function like
```js
function mapDispatchToProps( dispatch, ownProps ) {
  return bindActionCreators({
     update: ownProps.updateAction
   }, dispatch );
}
```
Whereas the updateAction property would be an action creator like:
```js
function createUpdateAction() {
   return function dispatchConcreteAction( dispatch, getState ) {
     let state = getState();
     let currentActionParams = actionParamSelectors.map( selector => selector(state) );
     dispatch( actualActionCreator( ...currentActionParams ) );
   }
}
```
Wa are not 100% sure if the second approach is a correct use-case for the thunk-middleware.

If so we can provide a well formulated example for the Readme.

**Comment by gaearon** [comment]
Sorry, this is redux-thunk repo.
Did you mean to file it here? 

https://github.com/gaearon/react-redux

**Comment by PSpSynedra** [comment]
@gaeron I this is the correct repo as we wanted to know if the thunk-middleware was the correct place to do store dependent action-parameter resolving.

For now we are resolving the store dependent action-parameters in the thunk-middleware via selectors, pass them to the actual action creator and dispatch them via the provided dispatcher.

I think that's an acceptable pattern that solves our requirements.

**Comment by gaearon** [comment]
Oh I understand now, thanks. I think there was a reselect issue about supporting selectors with arity, you might want to chime in there!

**Comment by ohtangza** [comment]
@PSpSynedra Did you get any answer for this?
