### ISSUE TITLE
index.d.ts does not come with 2.1.0

### ISSUE THREAD

**Issue by dannycochran** [gaearon/redux-thunk#120]
Right now getting the redux-thunk typings is a little tricky.

Doing:

`
npm install --save-dev @types/redux-thunk
`

will result in an empty types package that says "types now ship with redux-thunk"

but the latest version in the npm registry (2.1.0), and the corresponding branch here, do not include those typings, so I'm currently copying and pasting them in manually.

can the owners release a new version, maybe 2.1.1, that includes the typings?

**Comment by MartinMajewski** [comment]
Yupp, just what I have noticed right now... No index.d.ts inside the redux-thunk node module...

**Comment by unindented** [comment]
@aikoven do you know what could be happening?

**Comment by olee** [comment]
Same problem here - had to copy the index.d.ts into my project manually to get it working.

**Comment by seansfkelley** [comment]
This seems to be redundant with #109, but in any case, the [workaround mentioned there](https://github.com/gaearon/redux-thunk/issues/109#issuecomment-267078046) worked for me (though it's entirely nonobvious).

**Comment by timsuchanek** [comment]
@aikoven @gaearon Would be awesome if you just bump the npm version, because after the typescript definitions had been added in b0ec79cabeb498e389a3d41a723031fc4047b236, there was no version bump, so the change is not yet on npm.

**Comment by HeroicAutodidact** [comment]
This is happening to me too. Probably because `index.d.ts` isn't present in the commit tagged as `2.1.0` on github.

Seems like you guys just need to push another patch version, no?

**Comment by aikoven** [comment]
Released [v2.1.1](https://github.com/gaearon/redux-thunk/releases/tag/v2.1.1) with TypeScript definitions included.
