### ISSUE TITLE
Thunk not dispatching in returned promise

### ISSUE THREAD

**Issue by drunkengranite** [gaearon/redux-thunk#129]
So I'm using axios to return promises (in this case an array twitch feeds) and the dispatch is not 
happening inside of the then() clause of the actions, even though the console.log(streams)  gets the full object and prints it out.

My UI is react for the record. 

Do I need to pass in the dispatch into the promise parameter? or is this a bug?

I need help plox. I've included everything including the createStore funct
<img width="1680" alt="screen shot 2017-02-14 at 1 36 23 pm" src="https://cloud.githubusercontent.com/assets/10015258/22950527/c424d7ea-f2ba-11e6-9f19-278bb4131c48.png">
<img width="1680" alt="screen shot 2017-02-14 at 1 36 31 pm" src="https://cloud.githubusercontent.com/assets/10015258/22950529/c52e342e-f2ba-11e6-9b6b-98cd230230c6.png">
<img width="1680" alt="screen shot 2017-02-14 at 1 36 43 pm" src="https://cloud.githubusercontent.com/assets/10015258/22950536/c92c36f2-f2ba-11e6-8c74-f2aa1f71a4e0.png">
<img width="1680" alt="screen shot 2017-02-14 at 1 36 49 pm" src="https://cloud.githubusercontent.com/assets/10015258/22950542/cbc9ae8a-f2ba-11e6-9a99-4d3ccefa3564.png">

**Comment by alexlukelevy** [comment]
@drunkengranite did you ever find the solution to this issue?
