### ISSUE TITLE
Flux Standard Actions compatibility

### ISSUE THREAD

**Issue by artemjackson** [gaearon/redux-thunk#131]
It would be cool to have a support for SFA.
In that case it will be much easier to combine `redux-thunk` with some nice projects like `redux-actions` and `redux-promise-middleware`.

Example of  using a combination of `redux-actions`, `redux-promise-middleware` and `redux-thunk` :
```
export const login = createAction(LOGIN, (credentials) => async (dispatch, getState) => {
    if (getState().user.isLoggedIn) {
      await dispatch(logout());
    }

    return api.login(credentials);
});

// LOGOUT_PENDING
// LOGOUT_FULFILLED
// LOGIN_PENDING
// LOGIN_FULFILLED
```

There are even two PR's (you can choose any): https://github.com/gaearon/redux-thunk/pull/130 and https://github.com/gaearon/redux-thunk/pull/105

**Comment by gaearon** [comment]
Redux Thunk was always meant to be super simple. I’m not convinced we need to add more to it. Adding this is likely to help some people, but is also likely to break some other projects in weird ways where middlewares previously relied on Thunk ignoring objects. So I’d encourage you to fork `redux-thunk` as `redux-thunk-fsa` or something. If it becomes popular we can reconsider.

**Comment by artemjackson** [comment]
There are already several projects provide such functionality like
https://github.com/jtpalmer/redux-fsa-thunk
https://github.com/makeomatic/redux-thunk
https://github.com/ShMcK/redux-action-thunk

Existing of such project plus PR https://github.com/gaearon/redux-thunk/pull/105 from @bshy522 show the necessity of compatibility with FSA.
