### ISSUE TITLE
Unionize "Dispatch" augmentation, to allow for "Action" and "ThunkAction" arguments

### ISSUE THREAD

**Issue by begincalendar** [gaearon/redux-thunk#135]
Why does the TypeScript `Dispatch` interface augmentation only allow for async action parameters?

TypeScript seems to be able to use choose the appropriate definition of `Dispatch` when `dispatch()` is invoked with an argument that is **one of**: a traditional `Action` Object or an async action (function).

Yet if the argument is a union type (`Action | ThunkAction<...>`), then the compiler trips up.

I believe this can be solved by changing the way redux-thunk augments the `Dispatch` interface, so instead of being the way it is now, it should be:

```
interface Dispatch<S> {
  <A extends Action, R, E>(action: ThunkAction<R, S, E> | A): R | A;
}
```

Are there any reasons why this change should/can not happen?

**Comment by begincalendar** [comment]
So it seems the problem is even deeper, because if you add the following lines to "test/typescript.ts" (without touching the "index.d.ts" file):

```
declare const temp: ThunkAction<void, number, void>;
store.dispatch(temp);
```

...you get the following error:

```
Uncaught AssertionError: Semantic: /usr/local/src/redux-thunk/test/typescript.ts (38,16): Argument of type '(dispatch: Dispatch<number>, getState: () => number, extraArgument: void) => void' is not assignable to parameter of type 'Action'.
  Property 'type' is missing in type '(dispatch: Dispatch<number>, getState: () => number, extraArgument: void) => void'.
```

I think #118 would address these issues, but then I do agree it would break the foundational Redux rule that Action objects should be serializable.

I'm personally going to roll my own version of redux-thunk, breaking the need to have Action objects that are serializable (as I've already done that in my project anyway).

Not sure how these issues are going to be resolved for the community under the current constraints.

**Comment by davidspiess** [comment]
Maybe this is a solution?
http://stackoverflow.com/questions/43013204/how-to-dispatch-an-action-or-a-thunkaction-in-typescript-with-redux-thunk
