### ISSUE TITLE
Recieving async messages, can I detect when reducer is done?

### ISSUE THREAD

**Issue by pizza2code** [gaearon/redux-thunk#139]
Hi, I'm using a bridge between Java and JavaScript (jxBrowser).  I constantly receive status messages from this bridge, and sometimes Redux throws "reducers may not dispatch actions", despite the fact that the string "dispatch" occurs nowhere in my reducers.  I'm pretty certain that these messages are received in the middle of an existing reducer action.

Can I use redux-thunk to async dispatch my action once the reducer is finished?  How would I detect that the reducer is done?

**Comment by ttamminen** [comment]
Correct if I am wrong, but if you do

```
dispatch(someActionCreator())
dispatch(someActionCreator2())
```

In the second line, it is guaranteed that the reducer has processed the first action. It is a synchronous operation in a single threaded environment. But as I said, please do correct me if I am wrong or if I didn't understand the question.

**Comment by pizza2code** [comment]
Correct, but the Java bridge also calls back to JavaScript functions which dispatch. So those dispatch calls occur asynchronously, as soon as messages arrive, rather than the sequential example which you give.

I ended up solving the situation by writing my own middleware that starts the message listener and then dispatches actions on the JS event queue by passing it through setTimeout().  Not sure why the setTimeout call was necessary even with writing middleware, but since I have a solution I'll go ahead and close this issue.
