### ISSUE TITLE
TypeError: middleware is not a function

### ISSUE THREAD

**Issue by furkankadioglu** [gaearon/redux-thunk#144]
Hello, 

I'm trying to create a middleware. Giving this error: TypeError: middleware is not a function

Here is my code block:
```
import { applyMiddleware, createStore } from "redux"

import logger from "redux-logger"
import thunk from 'redux-thunk';
import promise from "redux-promise-middleware"

import reducer from "./reducers"

const middleware = [promise(), thunk, logger() ]

export default createStore(reducer, applyMiddleware(...middleware));
```

Here is my error:
![screen shot 2017-06-05 at 03 29 24](https://cloud.githubusercontent.com/assets/5060068/26766690/41b64294-499f-11e7-9443-bc7aa598f9e6.png)

I'm pretty sure i added react-redux and react-thunk on my project. Why giving this error?

**Comment by LAMike310** [comment]
How did you fix this @furkankadioglu?

**Comment by savovsky** [comment]
@LAMike310 Pls check my comment under: https://github.com/gaearon/redux-thunk/issues/35

**Comment by tuncakyazi** [comment]
I experienced the same problem. And solve by defining xx as default.

`import { default as ReduxThunk } from 'redux-thunk';`

**Comment by phuocantd** [comment]
I think change 
*import logger from "redux-logger"*
*import thunk from 'redux-thunk';*
*import promise from "redux-promise-middleware"*
to
**import { createLogger } from 'redux-logger'**
**import thunk from 'redux-thunk'**
**import { createPromise } from 'redux-promise-middleware'**
and change **applyMiddleware(createPromise(), thunk, createLogger())**

**Comment by nada-aldubaie2** [comment]
thunk must be import default 
`import { thunk } from "redux-thunk";
`
