### ISSUE TITLE
`next` is not a function with redux@2.0.0

### ISSUE THREAD

**Issue by MichaelHirn** [gaearon/redux-thunk#15]
After I made upgrades on npm as described down below, `redux-thunk@0.1.0` threw the error `next is not a function` on line 12 of the index.js.

*Upgrades*:
```
redux: 1.0.1 -> 2.0.0
react-redux: 1.0.1 -> 2.1.0
redux-devtools: 1.1.0 -> 2.1.0
```

Once I rolled back to 1.x.x, everything worked again as expected.

*__Update__*: Ok, just looked at the code. I probably could have dropped the line number.

**Comment by gaearon** [comment]
My guess is that you didn't apply this change from [Redux 2.0 release notes](https://github.com/rackt/redux/releases/tag/v2.0.0):

<img width="367" alt="screen shot 2015-09-07 at 02 52 57" src="https://cloud.githubusercontent.com/assets/810438/9707299/a8ab08e8-550b-11e5-8f0c-f7e41dd78218.png">

If this is not the problem please provide a project reproducing the issue.
