### ISSUE TITLE
Export createThunkMiddleware alongside singleton

### ISSUE THREAD

**Issue by dyst5422** [gaearon/redux-thunk#158]
I write many components that have their own redux stores intended to be able to be dropped into any react application without the need to wire-up to some top level redux store. Because redux-thunk exports as a singleton, any redux stores that use this will end up having their actions all merged together.

Can the createThunkMiddleware be exported alongside the default export to allow for this kind of use? Or, like many redux middlewares do, make the default export a function returning the middleware

**Comment by TrySound** [comment]
What the problem with this?
```js
import thunk from 'redux-thunk';
thunk.withExtraArgument();
```

**Comment by dyst5422** [comment]
Wow, I completely misunderstood the assignment that was happening there. Closing
