### ISSUE TITLE
applyMiddleware() just ignored? Docs (edit: _not_) followed letter by letter

### ISSUE THREAD

**Issue by DavideValdo** [gaearon/redux-thunk#164]
Please take a look at this:

https://github.com/reactjs/redux/issues/2683

The **same** technique is working for me in React Native, just not ReactJS.

**Comment by markerikson** [comment]
Resolved in the other issue.  The error was not actually calling the thunk action creators (ie, `dispatch(someThunk)` when it should be `dispatch(someThunk())`.

**Comment by DavideValdo** [comment]
Thanks, finally made it clear for me. REally sorry about this kind of hysteria :)
