### ISSUE TITLE
Why would you write an action creator that performs dispatch?

### ISSUE THREAD

**Issue by dminkovsky** [gaearon/redux-thunk#17]
"An action creator that returns a function to perform conditional dispatch"

An "action creator"—an interface, or concept, defined entirely in English prose—is a function that returns actions: objects that have a key "type".

Now, in this repository, this interface is being bent to return a function with some specific signature that furthermore performs dispatch. Such a returned function is no longer an "action" so the function that returns such a function is not an action creator; not even in the sense that a thunk is the functional representation of some expression, because:

action: 

```
{ type: SOMETHING }
```

action-thunk:

```
() => { type: SOMETHING }
```

I am writing this principally because I think Redux is great but the Redux docs and ecosystem have way too many things like "action creator" that are not actually part of the Redux API. These things seem to be some attempt to create a set of community-understood concepts related to Redux, but given that they are not part of the API—an API that is already built on top a dynamic language—they only serve to cloud the whole picture and are amenable to haphazardly abuse via prose by way of Markdown file.

**Comment by dminkovsky** [comment]
What I'm trying to say is that I find the Redux docs frustrating because there is a plethora of totally unnecessary symbol names literally all about the examples:

```
function makeASandwich(forPerson, secretSauce) {
  return {
    type: 'MAKE_SANDWICH',
    forPerson,
    secretSauce
  };
}

function apologize(fromPerson, toPerson, error) {
  return {
    type: 'APOLOGIZE',
    fromPerson,
    toPerson,
    error
  };
}

function withdrawMoney(amount) {
  return {
    type: 'WITHDRAW',
    amount
  };
}
```

introduces `makeASandwich`, `apologize` and `withdrawMoney`. The more symbol names you make, the more your reader has to keep track of them in your example. And all for this attempt to establish the concept of "action creator" for something that is really just a "helper function"—a thing that all programmers use all the time.

**Comment by dminkovsky** [comment]
"For example, redux-thunk lets the action creators invert control by dispatching functions." 😳

**Comment by gaearon** [comment]
Please send a PR docs if you see a better way to phrase or explain something. ;-)

**Comment by dminkovsky** [comment]
Okay :): https://github.com/rackt/redux/pull/745/commits

I mean, if I could, I would cut out half of the docs. I mean, the advanced middleware documentation goes through a 7-step motivational exercise? I would guess almost everyone reading Redux docs knows about middleware, either via Express or via Django. Ironically, I would further guess that terms like "monkeypatching" are far less common knowledge among readers, given that the term originates in the Ruby community!

AND THEN—you go to to `applyMiddleware` "API docs" only to be greeted by an enormous `redux-thunk` example, with basic logging buried at the end (my pull request fixes this). 

If it was up to me, I would remove that thunk example for the `applyMiddleware` docs altogether. That's not what API documentation is all about.

**Comment by gaearon** [comment]
@dminkovsky 

The docs were written over a period of one and a half months, and this is the reason for most inconsistencies. For example, Async Actions section was the last to be added. Because there weren't any other docs on async actions back then I had to add some examples to `applyMiddleware` as last resort.

I'm happy to see an issue discussing your plan to cutting duplications in docs.

**Comment by dminkovsky** [comment]
Oh I get I can imagine how such a base of documentation has emerged. I don't mean to be critical of the docs in that regard.

I'll open the ticket there.

Thank you.

**Comment by gaearon** [comment]
Thanks! Yes, it's concerning me too, but I'm busy with other stuff now so I can really appreciate somebody taking over this and getting docs into a less wordy / more consistent shape.
