### ISSUE TITLE
Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by iamyardem** [gaearon/redux-thunk#172]
npm 5.6.0
node 8.40
react 16.2.0
redux 3.7.2
redux-thunk 2.2.0

I receiving the following error while invoking thunk in react component, but when I simply dispatching similar function directly via store.dispatch it works fine.

Here is how I configured middleware

```javascript
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from '../reducers';

/* eslint-disable */
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

export function configureStore(initialState) {
  const store = createStore(
    rootReducer,
    initialState,
    composeEnhancers(
      applyMiddleware(thunk),
    ),
  );

  return store;
}
```

This is an index.html file with testAsync function which works fine

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import App from './containers/App';
import { Provider } from 'react-redux';
import { configureStore } from './helpers/store-helper';

import './base.scss';

function testAsync() {
  return (dispatch) => {
    setTimeout(() => dispatch({ type: 'TEST_ACTION' }), 1000);
  };
}

const store = configureStore();
store.dispatch(testAsync());

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root'),
);
```

This is the react component that throws that error

```javascript
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';

function getProduct() {
  return (dispatch) => {
    setTimeout(() => dispatch({ type: 'GET_PRODUCT' }), 1000);
  };
}

const mapStateToProps = state => state.productsPage;
const mapDispatchToProps = dispatch => ({
  onPageLoad: () => dispatch(getProduct()),
});

class ProductsPage extends Component {
  componentDidMount() {
    this.props.onPageLoad();
  }

  render() {
    return (
      <h1>Hello World</h1>
    );
  }
}

ProductsPage.propTypes = {
  onPageLoad: PropTypes.func,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(ProductsPage);
```

I've tried to debug this issue and I noticed that when testAsync starts executing, it goes through thunk middleware but getProducts skips this middleware somehow and fails on isPlainObject type check because dispatch function receives thunk function but not a plain object.

**Comment by maaland** [comment]
Hi

I'm having the same issue. Did you figure out where the problem was?

**Comment by iamyardem** [comment]
@maaland make sure you have only one store initialized. I had created two stores accidentally, and one of them had not redux thunk middleware

**Comment by maaland** [comment]
Right before you responded I realized that I did exactly that. Embarrassing...

Thanks!

**Comment by jsaya01** [comment]
Hello, 

Wondering if you would be able to share your updated code? I am having the same issue and cannot seem to figure out the problem.

Any help would be awesome thank you.

**Comment by jsaya01** [comment]
@maaland, thanks I appreciate the response.

**Comment by brunomacedo** [comment]
@maaland,

Thanks.

**Comment by alqusi1992** [comment]
I have the same issue too
