### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bithavoc** [gaearon/redux-thunk#174]
I'm seeing a lot of pull requests with mentions and @gaearon never replies.

@gaearon what's the status of this project?

I don't mean to be rude but redux-saga followers are citing the activity of this repo as one of the reasons devs should be switching over sagas.

**Comment by gaearon** [comment]
The project is literally 15 lines.

It can't be "dead" because it's just a tiny helper. There's no plans to develop it further, expand the API, etc.

The project isn't "dead", it's done. Redux Saga is a cool project but its scope is drastically larger.
