### ISSUE TITLE
Any examples for thunk middleware dispatching

### ISSUE THREAD

**Issue by vojtatranta** [gaearon/redux-thunk#21]
Do we know about any real-world examples of testing async action creators?
I struggle to test creators like this:
```js
function add(entity) {
  return dispatch => {
    dispatch({
     type: ADD,
    payload: entity
   })
  }
}
```
I looked at test here, but it gave me no clue.
Do I have to mock dispatch function or something?

**Comment by gaearon** [comment]
It depends on what you want to test. Mocking `dispatch` is reasonable.
Please see https://github.com/rackt/redux/issues/546.
