### ISSUE TITLE
Clarify on dispatch handling..

### ISSUE THREAD

**Issue by tracker1** [gaearon/redux-thunk#25]
Okay, I'm just curious if `dispatch(null)` would work without actually running any resolvers?

What I'm wanting to do, is something like...

    dispatch(getArticleHeader(someId));
    ...
    dispatch(getArticleHeader(someId));

where `getArticleHeader(someId)` will immediately return `{type:'GOT_ARTICLE_HEADERS',headers:[{id:...}]}` if it has the data locally, otherwise return null, but add the id to a queue, that will be rollup several id's into a single request to the remote service, then dispatching the joint result.

In this way, I can render results, but have loading status for any id's that don't yet have their details ready.

**Comment by gaearon** [comment]
Instead of returning `null` why not just *not* call `dispatch` from the inner function?

```js
function getArticleHeader(someId) {
  return (dispatch, getState()) => {
    if (getState(). /* some condition based on state */) {
      dispatch({ type: 'GOT_ARTICLE_HEADERS' });
    } else {
      // Something you wanna do
    }
  };
}

// ...
dispatch(getArticleHeader(someId));
// ...
dispatch(getArticleHeader(someId));
```
