### ISSUE TITLE
timeout demo ?

### ISSUE THREAD

**Issue by mydearxym** [gaearon/redux-thunk#27]
amazing work !

is there a timeout solution/option ?

**Comment by gaearon** [comment]
Hi, can you please provide more details?
I'm not sure what you're asking exactly.

**Comment by mydearxym** [comment]
@gaearon  sorry for my confusion,  what i want ask is how to handle a timeout situation ,  like a timeout request or operation  etc ...

**Comment by gaearon** [comment]
Please ask usage questions on StackOverflow.
