### ISSUE TITLE
getState and impurity

### ISSUE THREAD

**Issue by gyzerok** [gaearon/redux-thunk#3]
Why do we need to pass ```getState``` function instead of directly pass current state? Since that our actions becomes impure.

**Comment by gaearon** [comment]
Because people do async inside thunk action creators, and by the time async call is over, the state might have changed. Do you see a better solution here?

**Comment by gyzerok** [comment]
Sorry for a stupid question but do Redux guarantee dispatch order? If so nothing cant break if we would pass state directly.

**Comment by gaearon** [comment]
The thunk form is used for async calls:

```js
function incrementAsync() {
  return (dispatch, getState) => {
    doVeryLongAPICall().then(result => {
      // by this point state may have changed
      dispatch(...);
    });
  };
}
```

Redux can't (and shouldn't) block your app from working while API call is being performed.
