### ISSUE TITLE
Support of TypeScript 

### ISSUE THREAD

**Issue by nizsheanez** [gaearon/redux-thunk#31]
Is here any plan to add definitions to http://definitelytyped.org/ ?

**Comment by nizsheanez** [comment]
found, sorry.

**Comment by johnjelinek** [comment]
do note: definitelytyped is on the way out. TypeScript will now look in the repo for a `*.d.ts` file. Could this file be added to the repo here?

**Comment by nizsheanez** [comment]
it exists https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/redux-thunk

**Comment by johnjelinek** [comment]
@nizsheanez: It exists, but DefinitelyTyped is deprecated, so updates may not be found there. The `.d.ts` file should really be found in this repo.
