### ISSUE TITLE
Thunked action should be passed on to next middleware

### ISSUE THREAD

**Issue by tesujimath** [gaearon/redux-thunk#32]
This came up in discussion of pburtchaell/redux-promise-middleware#24.

In order to be able to use both redux-thunk and redux-promise-middleware in combination, it is important for the thunk middleware to pass on it's thunked action to the next middleware.  So to fix my problem, I had to change the thunk middleware from this:
```
export default function thunkMiddleware({ dispatch, getState }) {
  return next => action =>
    typeof action === 'function' ?
      action(dispatch, getState) :
      next(action);
}
```
to this:
```
function myThunkMiddleware({ dispatch, getState }) {
  return next => action =>
    typeof action === 'function' ?
      next(action(dispatch, getState)) :
      next(action);
}
```
That seems like a generally useful improvement, and I can't think of any reason not to do it.

Please see the referenced issue for the full discussion.

**Comment by tesujimath** [comment]
I just found a way to solve my problem with the existing redux-thunk behaviour, as now documented in pburtchaell/redux-promise-middleware#24.  So no change is needed here.

I've clearly just been learning how to use redux-thunk correctly.  Sorry about that.

I wonder if it's worth adding a note or example to the README?  What originally looked like a bug/misfeature in redux-thunk now appears to be a design decision.

**Comment by sai-prasanna** [comment]
Am I wrong in assuming that middleware should pass the action to next middleware?

I have a doubt, if the async actions in thunk call dispatch directly, and this middleware doesnot pass it , how does logger get the actual action being dispatched?

**Comment by gaearon** [comment]
>Am I wrong in assuming that middleware should pass the action to next middleware?

You're not wrong, this is what happens. However `dispatch` given to you by Redux Thunk will restart the middleware chain. This is on purpose: you might dispatch one thunk from another thunk.

>I have a doubt, if the async actions in thunk call dispatch directly, and this middleware doesnot pass it , If i want to log the actual action objects dispatched to store using logger, how does logger get the actual action being dispatched?


Put the logger last in the middleware chain. Then it will get all action objects just before they reach the reducer.

**Comment by sai-prasanna** [comment]
Thanks, I didnt notice at first that th dispatch method from applyMiddleware  actually points to the beginning of entire middleware chain in redux implementation..
