### ISSUE TITLE
middleware is not a function

### ISSUE THREAD

**Issue by johnjelinek** [gaearon/redux-thunk#35]
I can't tell if this is a `redux-thunk` or a `redux` issue.

I have a store like this:
```
const store = compose(
    applyMiddleware(
        thunk,
        logger
    )
)(createStore)(counter);
```

This results in an error message:
```
./node_modules/redux/lib/utils/applyMiddleware.js:50
        return middleware(middlewareAPI);
               ^

TypeError: middleware is not a function
    at ./node_modules/redux/lib/utils/applyMiddleware.js:50:16
    at Array.map (native)
    at ./node_modules/redux/lib/utils/applyMiddleware.js:49:27
    at Object.<anonymous> (./index.js:63:105)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
```

If I comment out `thunk` above, it continues:
```
const store = compose(
    applyMiddleware(
        // thunk,
        logger
    )
)(createStore)(counter);

store.dispatch({ type: INCREMENT });
store.dispatch({ type: INCREMENT });
store.dispatch({ type: DECREMENT });
```

```
$ node --harmony_default_parameters --harmony_destructuring index.js
will dispatch { type: 'INCREMENT' }
state after dispatch 1
will dispatch { type: 'INCREMENT' }
state after dispatch 2
will dispatch { type: 'DECREMENT' }
state after dispatch 1
```

**Comment by johnjelinek** [comment]
for reference, logger is defined as follows:
```
function logger({ getState }) {
    "use strict";
    return (next) => (action) => {
        console.log("will dispatch", action);
        let returnValue = next(action);
        console.log("state after dispatch", getState());
        return returnValue;
    };
}
```

**Comment by johnjelinek** [comment]
hrmm ... very strange -- when I `console.log(thunk)` I get `undefined`.

**Comment by johnjelinek** [comment]
If I do `import * as thunk from "redux-thunk";` I can `console.log(thunk)` and get: `[Function: thunkMiddleware]`. However, if I `console.log(thunk.default)`, I get `undefined`.

**Comment by johnjelinek** [comment]
ah ha - https://github.com/Microsoft/TypeScript/issues/2242#issuecomment-92218146. Note: if you're using typescript instead of babel as your transpiler, you have to use `import thunkMiddleware = require("redux-thunk");` to get the `default` module.

**Comment by johnjelinek** [comment]
Also note: if you use the require above, `tsc` barfs about the transpile, but it does indeed execute:
```
Argument of type 'typeof "redux-thunk"' is not assignable to parameter of type 'Middleware'.
  Property 'name' is missing in type 'typeof "redux-thunk"'.
```

**Comment by johnjelinek** [comment]
Did I mention? This would be a great thing to add to the repo: https://github.com/gaearon/redux-thunk/issues/31#issuecomment-160767329. Maybe I'll add a PR.

**Comment by johnjelinek** [comment]
more reference on this here: https://angularclass.com/the-state-of-typescript-packages/

**Comment by fej121** [comment]
use  “import thunk from "redux-thunk";”
not “import {thunk} from "redux-thunk";”

**Comment by sbabeal** [comment]
That still doesn't fix the typing issues.  To use the import thunk syntax thunk should be exported as default.  If I change the export statement in the typing file to export defaut and get rid of the equal size, it works.  This is the same approach that redux-logger took.

![image](https://cloud.githubusercontent.com/assets/16666745/13548960/db990cfc-e2c1-11e5-9c37-acaa3e2f9920.png)

**Comment by sbabeal** [comment]
I just looked at the PR and it was already in this format.  While my typescript compiler 1.7.6 seems to accept either version, web storm 11 complains that thunk is not exported default.  And my understanding was that you couldn't use the import default syntax without declaring an default export.  Here is the info from the TypeScript specification.  So I do not understand why it was changed.  The only thing i can tell from this an the other issue is that web pack couldn't properly load the file based on the import statement which sounds like a webpack issue.  Could someone either correct my understanding of the TypeScript spec or reopen this issue?

![image](https://cloud.githubusercontent.com/assets/16666745/13549102/9dca101c-e2c4-11e5-8a54-7d752e3b7e39.png)

![image](https://cloud.githubusercontent.com/assets/16666745/13549104/a4065508-e2c4-11e5-9450-e578a5580896.png)

![image](https://cloud.githubusercontent.com/assets/16666745/13549106/abc70f94-e2c4-11e5-8f8a-a68219f55faa.png)

**Comment by gaearon** [comment]
Redux Thunk currently uses CommonJS.
It does not explicitly export a “default”.
We should probably start using ES modules internally and export a CommonJS compat build with `default` as the exported key, as well as an ES modules build, but this can only be done after bumping a version because it breaks backwards compat.

**Comment by born2net** [comment]
any fix for this as I still can't use Redux with systemjs, have to use commonjs with ng2 becuase of this as this works fine in commonjs:
```
import * as thunkMiddleware from 'redux-thunk';
```
but will fail with system.
tried 
```
use “import thunk from "redux-thunk";”
``` 
but no luck (yes using TypeScript as well)

regards

Sean

**Comment by born2net** [comment]
@johnjelinek I can't use require as I am trying to switch to systemjs from cjs so this wont work
```
import thunkMiddleware = require("redux-thunk")
```
any other workaround?

regards

**Comment by born2net** [comment]
@gaearon any idea when the fix of exporting default be put in place?

**Comment by gaearon** [comment]
@born2net 

I don’t understand what you’re trying to do.
You can either

```js
import thunk from 'redux-thunk'
```

in an ES modules environment, or

```js
var thunk = require('redux-thunk').default
```

in a CommonJS environment.

Why aren’t these cases working for you?

**Comment by gaearon** [comment]
Also make sure you’re using 2.x.

**Comment by gaearon** [comment]
https://github.com/gaearon/redux-thunk#note-on-2x-update

**Comment by born2net** [comment]
TX, you got it, I was one version behind... 2.x fixed it!!!!!

**Comment by gaearon** [comment]
Glad to hear it! Cheers.

**Comment by zourtney** [comment]
Here another permutation for anyone using `commonjs` modules with Typescript. Works for me... YMMV.

```
typings install redux-thunk --save
```

Then:

```javascript
import * as thunk from 'redux-thunk';

redux.createStore(rootReducer, applyMiddleware(
  thunk.default   // <-- the aforementioned `.default`
));
```

**Comment by Truedrog** [comment]
@zourtney i tried this also, but i cant do this
```
import {loadCourses} from './actions/courseActions';
store.dispatch(loadCourses());
```

```
export function loadCourses() {
  return function name(dispatch) {
    return courseApi.getAllCourses()
      .then(courses => {
        dispatch(loadCoursesSuccess(courses));
      })
      .catch(error => {
        throw (error);
      });
  };
}
```

[ts] Argument of type '(dispatch: any) => Promise<void>' is not assignable to parameter of type 'Action'.
  Property 'type' is missing in type '(dispatch: any) => Promise<void>'.
(alias) loadCourses(): (dispatch: any) => Promise<void>

**Comment by zourtney** [comment]
@Truedrog, I tried for a while but can't reproduce that. I can't tell if it's a problem with the code, or just incorrect typings...

At any rate, I don't think it's related to `import` / middleware hookup.

**Comment by atrauzzi** [comment]
Just a heads up, but this still appears to be an issue in some way shape or form.

The only way I've been able to work it out is by doing this:

```
import thunk from "redux-thunk";
const thunkMiddleware = (thunk as any).default;
```

**Comment by savovsky** [comment]
After facing recently same issue and none of the above worked for me I've tried with importing just {createLogger} that sorted the issue when new logger instance was passed to applyMiddleware.

``` Javascript
import { applyMiddleware, createStore } from 'redux';
import promise from "redux-promise-middleware";
import thunk from "redux-thunk"
import { createLogger } from "redux-logger";

import reducer from "./reducers";
const middleware = applyMiddleware(  promise(),  thunk,  createLogger() );
export default createStore(reducer, middleware);
```
Works under Typescript and Babel because in my attempts to isolate the route cause I've switched to each of them.   The issue is observed with latest redux packages at the time of my writing and solution is tested only against them

``` Javascript
"react-redux": "^5.0.5",
"redux": "^3.7.1",
"redux-logger": "^3.0.6",
"redux-promise-middleware": "^4.3.0",
"redux-thunk": "^2.2.0"
```

**Comment by anandhiyer** [comment]
Thank you @savovsky for your reply. i had same issue in one of my projects and got resolved.

**Comment by nguyentrithuc** [comment]
Thanks @savovsky  for your solution. It worked for me!

**Comment by NickSevens** [comment]
@mattdell facepalm +1, thanks for the `.default` hint :)

**Comment by jfroussel** [comment]
Thank you  oupsss ..

**Comment by nandorojo** [comment]
> use “import thunk from "redux-thunk";”
> not “import {thunk} from "redux-thunk";”

Thanks so much. Is there a way to make my linter recognize default imports properly? It's often at the core of these bugs. I found a [plugin](https://www.npmjs.com/package/eslint-plugin-import), but I'm not totally sure how to install it.

**Comment by somayeh-ghasemipour** [comment]
I had the same problem, and finally, I fixed the version of these dependencies to  :
react-redux@5.0.7
redux-thunk@2.3.0
redux@4.0.0

and it worked!

**Comment by HenryPineda** [comment]
I had the same problem with redux-thunk@2.3.0 I fixed it by doing the following.

1- By reading a little bit of documentation here: https://redux.js.org/recipes/configuring-your-store

2- By add the following code 

import {createStore, applyMiddleware, compose } from 'redux';
import thunkMiddleware  from 'redux-thunk';

const middlewareEnhancer = applyMiddleware(logger, thunkMiddleware );
const composedEnhancers = compose(middlewareEnhancer,window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__());

const store = createStore(rootReducer,undefined, composedEnhancers);

**Comment by Antonio-Riccelli** [comment]
I seem to have stumbled upon the same error, but I'm not using TypeScript or Logger, so not sure about possible solution.

```
import redux from "redux";
import thunk from "redux-thunk";
import axios from "axios";
const createStore = redux.createStore;
const applyMiddleware = redux.applyMiddleware;


const initialState = {
    loading: false,
    users: [],
    error: ''
};

const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED';
const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED';
const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

const fetchUsersRequest = () => {
    return {
        type: FETCH_USERS_REQUESTED,
    }
}

const fetchUsersSuccess = users => {
    return {
        type: FETCH_USERS_SUCCEEDED,
        payload: users
    }
}

const fetchUsersFailure = error => {
    return {
        type: FETCH_USERS_FAILED,
        payload: error
    }
}

const reducer = (state = initialState, action) => {
    switch(action.type) {
        case FETCH_USERS_REQUESTED:
            return {
                ...state,
                loading: true
            }
        case FETCH_USERS_FAILED:
            return {
                ...state,
                loading: false,
                error: payload.error
            }
        case FETCH_USERS_SUCCEEDED:
            return {
                ...state,
                loading: false,
                users: payload.users
            }
    }
}

const fetchUsers = () => {
    return function(dispatch) {
        try {
        const response = axios.get("https://jsonplaceholder.typicode.com/users");
        const users = response.data.map(users => users.id);
        displatch(fetchUsersSuccess(users));
    } catch (error) {
        console.log(error.message);
        dispatch(fetchUsersFailure(error.message));
    }
    }
}
const store = createStore(reducer, applyMiddleware(thunk));

store.subscribe(() => console.log(store.getState()));
store.dispatch(fetchUsers());
```

![image](https://user-images.githubusercontent.com/39813213/170821769-b000982b-7c73-4af1-bd3c-54a6cc204740.png)

**Comment by anisur2805** [comment]
Simply add **.default** to the **createStore** function and solve the error **Middlewareis not a function.** This solve my issue.

<img src="https://i.imgur.com/1IZlrv3.png"/>
