### ISSUE TITLE
Accessing store in thunk

### ISSUE THREAD

**Issue by JakeGinnivan** [gaearon/redux-thunk#42]
Not exactly sure where to put this issue, also I possibly have missed the correct pattern to do what I need. 

The scenario is I have reducers/action creators for different screens in my application. I then have a reducer/action creator for application context. This application you can have multiple accounts accessible at the same time, but only one selected.

At the screen level, I want to re-initialise the screen because a bunch of reference data on each screen is dependent on the context. Inside my INIT_SCREEN action creator I want to subscribe to changes in the store, then see if the account context has changed. So I have a cross state tree dependency.

What I want is:

``` js
export function initScreen() {
  return (dispatch, getState, store) => {
    let currentAccount = store.getState().context.account
    let sub = store.subscribe(() => {
      if (store.getState().context.account !== currentAccount) {
        sub()
        dispatch(initScreen)
      }
    })
    dispatch({type: INIT_SCREEN})
    // rest of screen init
  }
}
```

Well, that is what I think I want. Suggestions on a better way to solve this is welcome.

**Comment by JakeGinnivan** [comment]
Thinking through this I probably can use `componentWillReceiveProps` on the screen then if the context changes (which I will `@connect` to) then I can re-init screen?

**Comment by gaearon** [comment]
Yep. You might also try something like https://github.com/yelouafi/redux-saga.
