### ISSUE TITLE
.babelrc should not be in npm repo

### ISSUE THREAD

**Issue by alinz** [gaearon/redux-thunk#43]
I think `babelrc` is being published in npm which causes `react-native` app's to crash! It has been fixed in react-redux and redux. However this bug still exists in this module.

**Comment by jaunesarmiento** [comment]
+1

More discussion about this in https://github.com/facebook/react-native/issues/4062

**Comment by gaearon** [comment]
(Note: it's not so much _our_ bug as RN tooling issue. But I'm happy to push an update soon!)

**Comment by gaearon** [comment]
This should actually have already been fixed as of 1.0.2.

**Comment by alinz** [comment]
@gaearon thanks for your update.
