### ISSUE TITLE
Uncaught TypeError: dispatch(...).then is not a function

### ISSUE THREAD

**Issue by wenqiW** [gaearon/redux-thunk#47]

**Comment by wenqiW** [comment]
found it is not related with redux-thunk, please delete it. Sorry

**Comment by ericwooley** [comment]
@wenqiW What was it, I am having the same issue

**Comment by sun2rise** [comment]
@wenqiW, @ericwooley  i am having the same issue... where am i wrong?

**Comment by TrySound** [comment]
@sun2rise Did you return promise in action creator?

**Comment by sun2rise** [comment]
This is the object that i return from my action:
```js
return new Promise(function (resolve, reject) {
    resolve({
      type: types.STORE_MEDIA_DATA_AUDIO_TRACKS,
      payload: fixedData
    });
  });
```

and this is the error i got:
```
VM5118:1180 Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.
```

**Comment by TrySound** [comment]
@sun2rise Thunk isn't promise middleware. Your action creators can look like this
```js
const actionCreator = () => dispatch => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve();
    }, 10);
  }).then(() => {
    dispatch({ type: 'ACTION_TYPE' });
  });
};

store.dispatch(actionCreator()).then(() => {
  console.log('The end of poem');
});
```

**Comment by ericwooley** [comment]
For the record, my problem wasn't redux-thunk, it ended up being a different middle ware that was interfering with this.

**Comment by sun2rise** [comment]
So redux-thunk is only for timing stuff? i have to chain actions, should i use redux-promise? I have to wait for a very short operation to complete and then call the next action

**Comment by ericwooley** [comment]
@sun2rise If your having a similar problem to me, try disabling other middle wares and see if it works

IIRC the one that was the issue for me was the redux-localstorage middleware

**Comment by sun2rise** [comment]
thanks @ericwooley but i only (try to) use redux-thunk for now.. all i do is 
```js
applyMiddleware(thunk)
```
in my createStore function

**Comment by markbrocato** [comment]
I'm having this issue.  I tried removing all other middleware but that didn't fix it. It looks like the dispatch method is just returning the action object, not a promise.

**Comment by markbrocato** [comment]
The action is being returned from here: https://github.com/reactjs/redux/blob/master/src/createStore.js#L181
