### ISSUE TITLE
why pass (dispatch, getState) instead of (store) to thunks?

### ISSUE THREAD

**Issue by Kosta-Github** [gaearon/redux-thunk#48]
Is there a reason to only pass on `(dispatch, getStore)` explicitly to the `thunk` like you do:
```JavaScript
function thunkMiddleware({ dispatch, getState }) {
  return next => action =>
    typeof action === 'function'
      ? action(dispatch, getState)
      : next(action);
}
```

Why not implementing it with the same interface as redux `middleware`s use by passing the whole `store` to the `thunk`:
```JavaScript
function thunkMiddleware = store => next => action =>
  typeof action === 'function'
    ? action(store)
    : next(action);
```

**Comment by trunda** [comment]
Look at [this](https://github.com/rackt/redux/blob/master/src/applyMiddleware.js#L25). Only these two functions  (`dispatch ` and `getState`) are exposed to middleware.

**Comment by Kosta-Github** [comment]
not exactly, since the `action` takes either `dispatch` and `getState` as two arguments vs. just the `store` as one argument. But the one argument case would be more symmetric to the `middleware` interface...

**Comment by gaearon** [comment]
We wanted to have as little as possible typing in the simplest case (`dispatch => ...`).
I agree passing a subset of store API would be more symmetric but at this point I don't think it's worth changing.
