### ISSUE TITLE
default export

### ISSUE THREAD

**Issue by AvraamMavridis** [gaearon/redux-thunk#49]
Although `import  thunkMiddleware from 'redux-thunk';` works, some code inspection tools (e.g. Webstorm ) complain that `Default export is not declared in exported module`. I am not sure if this is an issue with the way that the export is defined in the middleware, or is something that e.g. Webstorm cannot catch.

**Comment by gaearon** [comment]
Not sure what's up but definitely not a problem on our end.

**Comment by gaearon** [comment]
Maybe the problem is that we don't make a real ES6 export.
Our export is currently CommonJS style.
We'll probably do a real ES6 export in 2.0 but there's no urge.

**Comment by AvraamMavridis** [comment]
@gaearon thx for clarifying it.
