### ISSUE TITLE
Getting error with TypeScript...

### ISSUE THREAD

**Issue by born2net** [gaearon/redux-thunk#51]
Hello,
I am getting: 

![capture](https://cloud.githubusercontent.com/assets/5090936/12559683/548f803c-c34b-11e5-84ca-138d08e52aa5.PNG)

when applying:
import thunkMiddleware from "redux-thunk"
let createStoreWithMiddleware = applyMiddleware(thunkMiddleware)(createStore);

any known issues?

regards

Sean

**Comment by born2net** [comment]
project is at: https://github.com/born2net/ng2Boilerplate

**Comment by born2net** [comment]
will get you a free Enterprise account at http://www.digitalsignage.com if you want as tx... :)
and remember to use the Redux branch

**Comment by gaearon** [comment]
It is definitely not a problem with this library.
There is not enough information to say what the issue is as you have not provided the source code.
Please feel free to take this to StackOverflow as it's a better place to ask usage questions.

**Comment by alexanderharm** [comment]
Import it like this:
`import {compose, createStore, applyMiddleware} from 'redux'`
`// important: use require for redux-thunk`
`import thunk = require('redux-thunk')`
`// setup like this`
`let createStoreWithMiddleware = compose(applyMiddleware(thunk))(createStore)`
`let store = createStoreWithMiddleware(rootReducer)`
I use it like this with Angular2. Also map 'redux-thunk' to your .js file in your SystemJS config.

**Comment by gaearon** [comment]
Interesting. Apparently TypeScript doesn't provide interop with CommonJS modules.
We will release Redux Thunk 2.0 later that will have a proper default export so that will be solved.

In the meantime, rather than

```js
let createStoreWithMiddleware = compose(applyMiddleware(thunk))(createStore)
let store = createStoreWithMiddleware(rootReducer)
```

you can write
```js
let store = createStore(
  rootReducer,
  applyMiddleware(thunk)
)
```

if you use Redux >= 3.1.0.

**Comment by alexanderharm** [comment]
OK thanks. I will look forward to the new release. Also SystemJS does not handle the process.env.NODE_ENV correctly if not bundled. A basic redux implementation in Angular2 can be found here: https://github.com/jhades/angular2-redux-store (helped me a lot).

**Comment by franleplant** [comment]
Sorry to step in but after 1 hour of trying to make Typescript and Redux work together your solution was the only one working @gaearon :

```javascript
let store = createStore(
  rootReducer,
  applyMiddleware(thunk)
)
```

I don't know if anyone else will find this useful or if this is the right place but that's all I got.

The error was this:

```
error TS2345: Argument of type '(...args: any[]) => (reducer: <A extends Action>(state: {}, action: A) => {}, preloadedState?: {}...' is not assignable to parameter of type '(next: (reducer: <A extends Action>(state: AppState, action: A) => AppState, preloadedState?: App...'.
  Type '(reducer: <A extends Action>(state: {}, action: A) => {}, preloadedState?: {}) => Store<{}>' is not assignable to type '(reducer: <A extends Action>(state: AppState, action: A) => AppState, preloadedState?: AppState) ...'.
    Type 'Store<{}>' is not assignable to type 'Store<AppState>'.
      Type '{}' is not assignable to type 'AppState'.
```

When using `compose`. It might be that `compose` type definition is broken in `@types/redux v3.6.31`

**Comment by aikoven** [comment]
@franleplant Maybe this will help: https://github.com/reactjs/redux/issues/1937

**Comment by franleplant** [comment]
Thanks a lot! I've tried that after reading through the Type definition
files (yeah, Im crazy like that) but it did not work. In any case not using
compose at all did the job.
Thanks Dan!

**Comment by emzero** [comment]
@franleplant I'm having the same problem using redux 3.6.0. Your solution works but how to add the devToolsExtension?

**Comment by franleplant** [comment]
If you have the time, the best thing to do is to report this to
Definitelytyped repo (good luck finding yourself around). Have you tried
the alternatives discussed in all these related issues?

**Comment by emzero** [comment]
I've found a way. Leaving it here in case anybody else needs it.

```ts
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(rootReducer, {}, composeEnhancers(
  applyMiddleware(thunk)
));
```
