### ISSUE TITLE
UMD Dist build?

### ISSUE THREAD

**Issue by arronmabrey** [gaearon/redux-thunk#58]
Hey @gaearon,

I'm trying to add redux-thunk to the jsdelivr CDN, would it be possible to add a minified UMD build as part of the npm package? Similar to how redux does it. e.g. `dist/redux.min.js`

-- Arron

**Comment by TrySound** [comment]
@arronmabrey Is it really so big for you?

**Comment by arronmabrey** [comment]
@TrySound Oh no the size is not personally a concern of mine, it's just part of their (jsdelivr CDN) guidelines for adding new projects.

The important part would be the UMD build bit, so it could be added straight on a page via script tag.

**Comment by gaearon** [comment]
Fixed by #57 and #59.
