### ISSUE TITLE
Redux-thunk causing infinite loop in React/Redux application

### ISSUE THREAD

**Issue by jbri7357** [gaearon/redux-thunk#62]
I'm working on a webapp that's utilizing React with Redux. I have posted a similar message at the redux-thunk Github, but I think this might possibly be a more general issue with Redux middleware. I am currently using Redux-Thunk in a manner very similar to the example found here:
http://redux.js.org/docs/advanced/ExampleRedditAPI.html

When running my app, I see the following error in Chrome:

```
Uncaught RangeError: Maximum call stack size exceeded
(anonymous function) @ index.js:10
dispatch @ applyMiddleware.js:44
(anonymous function) @ index.js:12
dispatch @ applyMiddleware.js:44
(anonymous function) @ index.js:12
dispatch @ applyMiddleware.js:44
(anonymous function) @ index.js:12
dispatch @ applyMiddleware.js:44
```

Here's a link to my project:
https://github.com/jbri7357/redux-sample-app

**Comment by bfink13** [comment]
Can you post your index.js?

**Comment by jbri7357** [comment]
I've attached my main.jsx (index.js) file as requested.

**Comment by jbri7357** [comment]
I've updated my code samples after doing some refactoring and I still see the same issue.

**Comment by jbri7357** [comment]
The problem has been located:

https://github.com/reactjs/redux/issues/1564
