### ISSUE TITLE
I need to bundle dispatches for performance reasons

### ISSUE THREAD

**Issue by l2silver** [gaearon/redux-thunk#65]
Basically, I'd like to beable to create a fake store that I can dispatch multiple actions to, change the fake state completely, and then send the fake store state to the real state. I need to do this because my react state is rendering whenever the state changes, which can be multiple times in a single thunk. This is leading to inefficiencies that I would like to resolve.

Thanks

**Comment by gaearon** [comment]
You might be interested in https://github.com/tappleby/redux-batched-subscribe/ and https://github.com/tshelburne/redux-batched-actions.

**Comment by l2silver** [comment]
THanks!
