### ISSUE TITLE
creating custom thunk middleware

### ISSUE THREAD

**Issue by necolas** [gaearon/redux-thunk#66]
Any interest in supporting more complex use cases for thunks (like injecting an API client)?

```js
const export myAction = (data) => (dispatch, getState, helpers) => {
  return helpers.client.get(PATH, options).then(doStuff);
}
```

Doesn't need to be a breaking change; we can export a factory:

```js 
export const createThunkMiddleware = (any) => ({ dispatch, getState }) => next => action => {
  if (typeof action === 'function') {
    return action(dispatch, getState, any);
  }
  return next(action);
};

export default createThunkMiddleware();
```

**Comment by gaearon** [comment]
I think it’s so small it doesn’t need to fit all use cases. By all means, use a custom one :wink: .

**Comment by langpavel** [comment]
@gaearon Your middleware is so nice! But real use cases need custom helpers.
Do you think about refactoring it for new version to provide single object instead of two functions?
I know, this is major version breaker, but so useful for real word.

**Comment by langpavel** [comment]
Thanks @gaearon. Looks like you hear me and implement this in #70. Thanks!

**Comment by gaearon** [comment]
Yea, sorry I didn’t give credit. 😄 
I saw a few more people doing this and figured it’s worth adding it without making it a breaking change.

**Comment by langpavel** [comment]
Don't worry about it, this is small change, most important is that it landed :-)
