### ISSUE TITLE
[Question]: what does thunk 2.x bring to the table?

### ISSUE THREAD

**Issue by toranb** [gaearon/redux-thunk#67]
First up - many thank you(s) for the greater redux ecosystem :) love all the amazing work you do and truly appreciate all you've given away (especially the wonderful egghead series).

Question - I've been using `redux-thunk` along with redux the last few months but noticed recently that this library is now in v2.0. I tried looking for a changelog or something to show "what is different / why upgrade" but didn't see anything explicit about the migration/etc.

For new users - what is the compelling reason to upgrade/what does 2.0 offer?

**Comment by gaearon** [comment]
We put all the release notes on the GitHub releases page:
https://github.com/gaearon/redux-thunk/releases

I hope this helps!

**Comment by toranb** [comment]
Thank you!
