### ISSUE TITLE
Thunk not working in Safari

### ISSUE THREAD

**Issue by ammichael** [gaearon/redux-thunk#86]
Hello there!

First, thanks for this awesome middleware (actually, for the whole Redux). Thanks a lot indeed, awesome job!

I ran into a strange bug. I'm using thunk and it's working like a charm.. except in Safari.

In Safari it just doesn't work at all. Whatever async action I dispatch, it does dispatch the action, but it doesn't 'reach' the reducer. it's like thunk isn't working at all, and I've got no idea what is happening here =(

I've got no console errors, and no ideas on how to debug that.

Here is the action:

```
import {FETCH_MELHORES} from './../const';
import APIService from '../../services/APIService';

module.exports = function(parameter) {
  let quantidade = 7;
  let offset = 0;

  const ultimosPosts = APIService.fetchUltimosPosts(quantidade, offset);
  console.log('fetchMelhores action')
  return (dispatch) => {
    ultimosPosts.then((data) => {
      console.log('FETCH_MELHORES data:')
      console.log(data)
      dispatch({type: FETCH_MELHORES,
                ultimosPosts: data,
                parameter})
    }).catch(err){
      console.log('fetchMelhores fetch error')
      console.log(err)
    }
  };
};
```

And here the store creator:

```
import { createStore, applyMiddleware, combineReducers, compose } from 'redux';
import thunk from 'redux-thunk';

const reducers = require('../reducers');
const createStoreWithMiddleware = applyMiddleware(thunk)(createStore);

module.exports = function(initialState) {
  // const store = createStoreWithMiddleware(reducers, initialState,
  // window.devToolsExtension && window.devToolsExtension())

  const store = createStore(
    reducers,
    initialState,
    compose(
      applyMiddleware(thunk)
    )
  )

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextReducer = require('../reducers')
      store.replaceReducer(nextReducer)
    })
  }

  return store
}
```

Again: it works perfectly in any browser, but not in Safari. 

Any ideas? 😞

Thx

**Comment by ammichael** [comment]
So what was happening: I was importing github's fetch polyfill into App.js and it worked in Chrome and Firefox. But not in Safari and IE.

My error.

**Comment by xiguaaxigua** [comment]
@ammichael Hi man, I got same problem. How did you solve it?

**Comment by ammichael** [comment]
@xiguaaxigua Hi there. I just started importing in every file I was using it. For some reason, in Chrome and Firefox importing once in the main file was enough, but in Safari it should be a little more decoupled or just isolated.

**Comment by irfiacre** [comment]
> @xiguaaxigua Hi there. I just started importing in every file I was using it. For some reason, in Chrome and Firefox importing once in the main file was enough, but in Safari it should be a little more decoupled or just isolated.

I have the same problem, but I am somehow confused here, may you be more descriptive.

Thanks
