### ISSUE TITLE
Order of middleware stack, and thunk

### ISSUE THREAD

**Issue by qnm** [gaearon/redux-thunk#9]
I've been debugging an issue for the last while, and the crux of the issue is that `thunk` sat further down the middleware stack than it should, causing me some rather opaque errors.

In particular, `devTools` ran before it, and was throwing an exception as it tried to interpret the result returned from an action creator.

My fix involved changing from this

```
const finalCreateStore = compose(
  devTools(),
  applyMiddleware(thunk),
  persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/)),
  createStore
);
```

to this

```
const finalCreateStore = compose(
  applyMiddleware(thunk),
  devTools(),
  persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/)),
  createStore
);
```

Is it worthwhile stating on the `README` that `thunk` must be run before other middleware, or is this issue specific to `devTools`?

**Comment by gaearon** [comment]
From http://gaearon.github.io/redux/docs/api/applyMiddleware.html:

>If you use other store enhancers in addition to applyMiddleware, make sure to put applyMiddleware before them in the composition chain because the middleware is potentially asynchronous. For example, it should go before redux-devtools because otherwise the DevTools won’t see the raw actions emitted by the Promise middleware and such.

But I agree it's not enough.
Can I ask you to contribute PR to amend README of redux-devtools to highlight this?

**Comment by qnm** [comment]
@gaearon Sure! I'll aim to get to it this week.

**Comment by gaearon** [comment]
Closing as inactive.

**Comment by dazlious** [comment]
https://github.com/gaearon/redux-thunk/pull/173
