### ISSUE TITLE
documentation: why not declarative effects

### ISSUE THREAD

**Issue by mheiber** [gaearon/redux-thunk#95]
@gaearon the APIs and implementations of Redux and redux-thunk seem incredibly intentional and well-thought-out. However, thunks are a total pain to test, since thunks are really opaque compared to declarative effects like those in redux-loop, redux-saga, redux-side-effect, etc. 

For example, in this code from the documentation, the thunk closes over `forPerson`. So it's in there, but the only way to test that it's in there is to mock `dispatch` and spy on `makeASandwich`:

```js
function makeASandwichWithSecretSauce(forPerson) {

  // Invert control!
  // Return a function that accepts `dispatch` so we can dispatch later.
  // Thunk middleware knows how to turn thunk async actions into actions.

  return function (dispatch) {
    return fetchSecretSauce().then(
      sauce => dispatch(makeASandwich(forPerson, sauce)),
      error => dispatch(apologize('The Sandwich Shop', forPerson, error))
    );
  };
}
```

A data structure like this is much easier to inspect:

```js
{
   func: makeASandwich,
   args: [forPerson, sauce]
}
```

Since you're familiar with elm and did so much to make Redux testable in general, was there a reason to not go with declarative side effects?

**Comment by gaearon** [comment]
This is easier to explain than declarative effects. It works OK for smaller projects that don’t care as much about testing. And it is close to what Flux apps used at the time, and we cared about making it easier to migrate off from Flux.

This is the first middleware for Redux ever created 😄 . So don’t expect wonders from it. It does its job, but has flaws you described, so don’t use it if it doesn’t fit your use case.

**Comment by mheiber** [comment]
@gaearon thanks for sharing the reasoning and for making redux-thunk: it worked well for us for a medium-sized project and testing was the only issue.
